### ISSUE TITLE
OSError: [Errno 121] Remote I/O error when using screen

### ISSUE THREAD

**Issue by mrjones-plip** [Ths2-9Y-LqJt6/cattmate#1]
Steps to reproduce
1. set up cattmate and start with a screen attached and enabled in config.py (`use_display = True`)
1. Adjust the volume a bunch 

expected: volume is adjusted and shown on screen
actual: volume stops being adjust and screen stops working  because of an error:

```python
send vol update: 9
Traceback (most recent call last):
  File "cattmate.py", line 112, in <module>
    main()
  File "cattmate.py", line 91, in main
    screen.display(current_volume)
  File "/home/pi/cattmate/Ssd1306.py", line 18, in display
    self.screen.begin()
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_SSD1306-1.6.2-py3.7.egg/Adafruit_SSD1306/SSD1306.py", line 148, in begin
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_SSD1306-1.6.2-py3.7.egg/Adafruit_SSD1306/SSD1306.py", line 247, in _initialize
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_SSD1306-1.6.2-py3.7.egg/Adafruit_SSD1306/SSD1306.py", line 129, in command
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_GPIO-1.0.4-py3.7.egg/Adafruit_GPIO/I2C.py", line 116, in write8
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_PureIO-0.2.3-py3.7.egg/Adafruit_PureIO/smbus.py", line 256, in write_byte_data
OSError: [Errno 121] Remote I/O error
```

I wonder if we're updating the screen too often? Right now it's getting updated every `cattmate_config.refresh_wait` which ships at `0.01` seconds ( 10ms) which maybe is too fast?

**Comment by mrjones-plip** [comment]
Huh - changing `cattmate_config.refresh_wait` to `1.0` (1000ms) doesn't seem to fix it.... Maybe we could put the calls to `ssd1306.display` in a try/except and do a retry some how?  See [this](https://stackoverflow.com/a/2083996) (simple) and [that](https://julien.danjou.info/python-retrying/)(complex) for a howto.

**Comment by mrjones-plip** [comment]
i just refactored the screen code in #2, so updated the stack trace above.  I put another defensive `time.sleep()` in there which didn't seem to help.  Oh...maybe if I increase it now to 100ms?  I'll try now ;)

**Comment by mrjones-plip** [comment]
interesting! at 500ms i'm still getting the error, so likely the timing theory as root cause isn't right.  Also, I saw it error on the first call to `screen.display()` (currently [line 75](https://github.com/Ths2-9Y-LqJt6/cattmate/blob/490a19b03b73d6c29aea2dc3553634c81d7f2b15/cattmate.py#L75)), which would be the very first update.  Maybe the screen gets wedged in a bad state some how? Oh...I'll try a totally different screen in case this specific piece of hardware is bad.  hadn't thought of that!

**Comment by mrjones-plip** [comment]
trying the same hardware still, but I noticed that it's erroring out in different spots in the class, just in case it's relevant:

```python
Traceback (most recent call last):
  File "cattmate.py", line 112, in <module>
    main()
  File "cattmate.py", line 103, in main
    screen.display(current_volume + ' ;)')
  File "/home/pi/cattmate/Ssd1306.py", line 51, in display
    self.screen.display()
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_SSD1306-1.6.2-py3.7.egg/Adafruit_SSD1306/SSD1306.py", line 167, in display
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_SSD1306-1.6.2-py3.7.egg/Adafruit_SSD1306/SSD1306.py", line 129, in command
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_GPIO-1.0.4-py3.7.egg/Adafruit_GPIO/I2C.py", line 116, in write8
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_PureIO-0.2.3-py3.7.egg/Adafruit_PureIO/smbus.py", line 256, in write_byte_data
OSError: [Errno 5] Input/output error
```

**Comment by mrjones-plip** [comment]
different screen and different jumper cables didn't fix it :(

**Comment by mrjones-plip** [comment]
refactored the class a 2nd time and still getting the error :(

```bash
Traceback (most recent call last):
  File "cattmate.py", line 113, in <module>
    main()
  File "cattmate.py", line 104, in main
    screen.display(current_volume + ' ;)')
  File "/home/pi/cattmate/Oled.py", line 72, in display
    self.disp.display()
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_SSD1306-1.6.2-py3.7.egg/Adafruit_SSD1306/SSD1306.py", line 167, in display
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_SSD1306-1.6.2-py3.7.egg/Adafruit_SSD1306/SSD1306.py", line 129, in command
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_GPIO-1.0.4-py3.7.egg/Adafruit_GPIO/I2C.py", line 116, in write8
  File "/usr/local/lib/python3.7/dist-packages/Adafruit_PureIO-0.2.3-py3.7.egg/Adafruit_PureIO/smbus.py", line 256, in write_byte_data
OSError: [Errno 5] Input/output error
```

However, I ran this class for 2+ hours in a simple `while True:` loop that just updated the screen with a random number and it didn't crash.  This bug has something to do with how we implemented it in `cattmate.py`

**Comment by mrjones-plip** [comment]
latest PR #5 seems to have fixed it?  Let's close and hope it has.
